# Runs every night, and downloads the daily 1m chart

name: Download 1m candles


on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *

jobs:
  Download-1m-candles:
    runs-on: ubuntu-latest
    steps:
      - run: echo "yey"

