# Runs every night, and downloads the daily 1m and 5m charts

name: download candles

on:
  scehdule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  download-candles:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v3

      - run: python3 download_candles.py

      - uses: stefanzweifel/git-auto-commit-action@v4

      - run: |
          cp -r ./candles_1m/ /home/ubuntu/candles_data/
          cp -r ./candles_5m/ /home/ubuntu/candles_data/
